name: pkgcheck

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Manually trigger the Action under Actions/pkgcheck
  workflow_dispatch:
  # Run on every push to main
  push:
    branches:
      - main

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RUN_OSRM_LIVE_TESTS: "true"
    permissions:
      contents: read
      issues: write
      pull-requests: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: ropensci-review-tools/pkgcheck-action@main
        continue-on-error: true
